### ISSUE TITLE
Glitches on some stairs, platform and pistol super jumping!

### ISSUE THREAD

**Issue by cipiricus** [pjasicek/CaptainClaw#6] opened 2017-04-22 11:28 UTC
Here is the video proofs of glitches with stairs, a platform and pistol super jumping, last two descovered accidentally... 

https://cloud.orange.ro/share/ef09f5c52fbd9c3d1cff48268b71b3ab09daa7984b474901

**Comment by pjasicek** [comment] 2017-04-22 11:38
Oh. I knew about the first 2 bugs with the ladders, this is a bug on my side and I plan to fix that.

Regarding the other bug, I did not know about that :D Thank you for the report, I will fix it soon.

**Comment by pjasicek** [comment] 2017-04-22 16:27
Climbing through ground fixed with https://github.com/pjasicek/CaptainClaw/commit/7d2d77195c5fd7e2944b8fe31f375914fe9ddfbc

The other bug I cannot reproduce, but I will try to fix it nonetheless.

**Closed by pjasicek** 2017-04-22 16:27 UTC

**Comment by cipiricus** [comment] 2017-04-22 18:36
It seems the pistol super jumping is fixed, thanks a lot
