### ISSUE TITLE
Error on start a level

### ISSUE THREAD

**Issue by italozaina** [pjasicek/CaptainClaw#90] opened 2017-08-17 13:37 UTC
~/CaptainClaw/Build_Release $ ./captainclaw
WARN: [RunGameEngine] Failed to set high priority class to this process
INFO: Looking for: /usr/share/captainclaw/config.xml
INFO: Looking for: config.xml
INFO: >>>>> Initializing display...
INFO: Display successfully initialized.
INFO: >>>>> Initializing audio...
INFO: Audio successfully initialized.
INFO: >>>>> Initializing font...
INFO: Font successfully initialized...
INFO: >>>>> Initializing resource cache...
INFO: Resource cache successfully initialized
INFO: >>>>> Loading actor prototypes...
INFO: Actor prototypes loaded successfully.
INFO: 1
INFO: 2
INFO: 3
INFO: 4
INFO: 5
INFO: 6
INFO: Changing to: 3
WARN: [GetSoundPathFromClawPath] Cannot convert sound: /LEVEL10/SOUNDS/TRIGGER/1013.WAV
[WWD->XML]: Elapsed microseconds: 108803
ERROR: [MEMORY_PROFILER] Memory profiler not supported on this platform !
ERROR: [ParseCollisionRectanglesFromTile] Collision rectangles are empty for tile: 902
Unknown Rect: X = 0, Y = 12, Width = 27, Height = 16
ERROR: [ParseCollisionRectanglesFromTile] Case 12: Tile 910 not implemented !
ERROR: [ParseCollisionRectanglesFromTile] Collision rectangles are empty for tile: 910
Unknown Rect: X = 32, Y = 12, Width = 31, Height = 16
ERROR: [ParseCollisionRectanglesFromTile] Case 12: Tile 912 not implemented !
ERROR: [ParseCollisionRectanglesFromTile] Collision rectangles are empty for tile: 912
Unknown Rect: X = 32, Y = 28, Width = 31, Height = 8
[PLANE CREATION]: Elapsed microseconds: 561
[PLANE CREATION]: Elapsed microseconds: 38001
[PLANE CREATION]: Elapsed microseconds: 1019
WARN: [CalculatePatrolBorders] Did not find raycastResultLeft intersection for actor: Level3_CutThroat with position: [X: 5697.000000, Y: 5837.000412]
WARN: [CalculatePatrolBorders] Did not find raycastResultLeft intersection for actor: Level3_RobberThief with position: [X: 5887.000000, Y: 5516.999992]
WARN: [CalculatePatrolBorders] Did not find raycastResultLeft intersection for actor: Level3_RobberThief with position: [X: 5710.000000, Y: 5261.000278]
WARN: [CalculatePatrolBorders] Did not find raycastResultLeft intersection for actor: Level3_CutThroat with position: [X: 20455.000000, Y: 4493.999916]
ERROR: [VPostPostInit] Failed to get raycast result down from position: [X: 19892.000000, Y: 3856.000000]
WARN: [CalculatePatrolBorders] Did not find raycastResultLeft intersection for actor: Level3_RobberThief with position: [X: 19892.000000, Y: 3856.000000]
WARN: [CalculatePatrolBorders] Did not find raycastResultLeft intersection for actor: Level3_RobberThief with position: [X: 20554.000000, Y: 3277.999950]
WARN: [CalculatePatrolBorders] Did not find raycastResultLeft intersection for actor: Level3_RobberThief with position: [X: 20168.000000, Y: 3149.999989]
WARN: [CalculatePatrolBorders] Did not find raycastResultLeft intersection for actor: Level3_CutThroat with position: [X: 20289.000000, Y: 2894.000134]
WARN: [CalculatePatrolBorders] Did not find raycastResultLeft intersection for actor: Level3_CutThroat with position: [X: 21184.000000, Y: 2894.000134]
WARN: [CalculatePatrolBorders] Did not find raycastResultLeft intersection for actor: Level3_CutThroat with position: [X: 21441.000000, Y: 2894.000065]
WARN: [CalculatePatrolBorders] Did not find raycastResultLeft intersection for actor: Level3_CutThroat with position: [X: 21376.000000, Y: 3993.999931]
WARN: [CalculatePatrolBorders] Did not find raycastResultLeft intersection for actor: Level3_Rat with position: [X: 20346.000000, Y: 3050.999846]
ERROR: [VPostInit] No animations in amin component. Offending actor: LEVEL_ARROWSIGN_RIGHT
ERROR: [VPostInit] No animations in amin component. Offending actor: LEVEL_ARROWSIGN_LR
ERROR: [VPostInit] No animations in amin component. Offending actor: LEVEL_ARROWSIGN_LR
ERROR: [VPostInit] No animations in amin component. Offending actor: LEVEL_ARROWSIGN_LR
ERROR: [VPostInit] No animations in amin component. Offending actor: LEVEL_ARROWSIGN_RIGHT
ERROR: [VPostInit] No animations in amin component. Offending actor: LEVEL_ARROWSIGN_LR
ERROR: [VPostInit] No animations in amin component. Offending actor: LEVEL_ARROWSIGN_RIGHT
ERROR: [VPostInit] No animations in amin component. Offending actor: LEVEL_ARROWSIGN_LR
WARN: [CalculatePatrolBorders] Did not find raycastResultLeft intersection for actor: Level3_RobberThief with position: [X: 20061.000000, Y: 4493.999939]
WARN: [CalculatePatrolBorders] Did not find raycastResultLeft intersection for actor: Level3_RobberThief with position: [X: 20323.000000, Y: 4172.999992]
WARN: [CalculatePatrolBorders] Did not find raycastResultLeft intersection for actor: Level3_RobberThief with position: [X: 19936.000000, Y: 4174.000027]
ERROR: [VPostInit] No animations in amin component. Offending actor: LEVEL_ARROWSIGN_LR
ERROR: [VPostInit] No animations in amin component. Offending actor: LEVEL_ARROWSIGN_LR
ERROR: [VPostInit] No animations in amin component. Offending actor: LEVEL_ARROWSIGN_UP
ERROR: [VPostInit] No animations in amin component. Offending actor: LEVEL_ARROWSIGN_LR
ERROR: [VPostInit] No animations in amin component. Offending actor: LEVEL_ARROWSIGN_LR
ERROR: [VPostInit] No animations in amin component. Offending actor: LEVEL_ARROWSIGN_UP
ERROR: [VPostInit] No animations in amin component. Offending actor: LEVEL_ARROWSIGN_LR
ERROR: [VPostInit] No animations in amin component. Offending actor: LEVEL_ARROWSIGN_RIGHT
ERROR: [VPostInit] No animations in amin component. Offending actor: LEVEL_ARROWSIGN_UP
ERROR: [VPostInit] No animations in amin component. Offending actor: LEVEL_ARROWSIGN_RIGHT
ERROR: [VPostInit] No animations in amin component. Offending actor: LEVEL_ARROWSIGN_UP
ERROR: [VPostInit] No animations in amin component. Offending actor: LEVEL_ARROWSIGN_RIGHT
ERROR: [VPostInit] No animations in amin component. Offending actor: LEVEL_STARTSKULLPOST
ERROR: [VPostInit] No animations in amin component. Offending actor: LEVEL_ARROWSIGN_UP
ERROR: [VPostInit] No animations in amin component. Offending actor: LEVEL_ARROWSIGN_RIGHT
ERROR: [VPostInit] No animations in amin component. Offending actor: LEVEL_ARROWSIGN_RIGHT
ERROR: [VPostInit] No animations in amin component. Offending actor: LEVEL_STARTSKULLPOST
ERROR: [VGetRawResourceSize] Could not locate: /game/images/ingamemenu/main/001_return.pid in rezArchive: CLAW.REZ
ERROR: [Load] Resource size return -1 => Resource not found. Resource: /game/images/ingamemenu/main/001_return.pid
Segmentation fault

**Comment by pjasicek** [comment] 2017-08-17 14:45
Welcome, thanks for report.

I myself cannot reproduce it neither on Windows nor Linux (Ubuntu 17.04). Which CLAW.REZ do you use ? Could you do send me its md5 or CRC32 so I  can compare if we use the same ?

**Comment by pjasicek** [comment] 2017-08-17 16:48
Same problem with your archive. Replace it with the one I posted and it should be fine.

**Comment by italozaina** [comment] 2017-08-17 19:16
I saw inside .rez file, the file still there, but with other extension (.pcx), and the load looking for (.pid). Could you do a by pass on this for me? Because all the game in my rez file is in my language (pt-br) and was working on other builds i did before.

By the way your project still amazing. xD

**Comment by italozaina** [comment] 2017-08-17 20:40
Ow i found some solution for my case, modify ASSETS folder xml for my .rez files recompress as zip and other change on Engine/UserInterface/UserInterface.cpp line 156
`pImage = PcxResourceLoader::LoadAndReturnImage(imagePath.c_str(), true, { 255, 0, 132, 255 });`

now looks great... https://www.youtube.com/watch?v=wBkO3evFzyY
Sorry for the inconvenience.

**Comment by pjasicek** [comment] 2017-08-17 20:48
Thanks for the investigation, I'm glad you figured it out. I didn't assume that other language versions have different file formats, but this would not be the first time I found some Monolith's hack 😄 .

I will add a fallback that if the *.PID fails to load, it will look for *.PCX, that should fix possible issues with other versions. 

The color key for transparent background issue - I am not sure how to generically figure it out. Maybe by taking a first pixel in some PCX image and getting its color key. I will think on it,

**Comment by pjasicek** [comment] 2017-08-21 15:37
Closing. Related issue regarding language support is here:

https://github.com/pjasicek/CaptainClaw/issues/99

**Closed by pjasicek** 2017-08-21 15:37 UTC
