### ISSUE TITLE
Claw stays alive on spikes

### ISSUE THREAD

**Issue by denispapec** [pjasicek/CaptainClaw#31] opened 2017-05-17 22:53 UTC
Got this issue once with https://github.com/pjasicek/CaptainClaw/commit/f714339800bd1c4291baa62b6a648e3e51f6fbdc as latest commit, can't replicate it anymore.
![clawb](https://cloud.githubusercontent.com/assets/5442891/26179306/e14590ce-3b5a-11e7-9799-09e6f6d54a2d.gif)

**Comment by pjasicek** [comment] 2017-05-18 04:33
Thanks for the report. I know that this happened few weeks ago and I fixed it. I haven't reproduced it since. I will keep an eye out for that and maybe test it for 50 deaths or so in different situations.

**Comment by cipiricus** [comment] 2017-05-18 16:18
I don't have that bug on Ubuntu OS

**Comment by pjasicek** [comment] 2017-05-20 20:48
Cannot reproduce. Closing for now. If this will reappear, make a new bug report please.

**Closed by pjasicek** 2017-05-20 20:48 UTC
Labels: bug
